apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gvisor-deploy.serviceAccountName" . }}
  namespace: {{ include "gvisor-deploy.namespace" . }}
  labels:
    {{- include "gvisor-deploy.labels" . | nindent 4 }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
